apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "logging-demo.fullname" . }}
spec:
  fluentd:
    {{- if .Values.loggingOperator.tls.enabled }}
    tls:
      enabled: true
      secretName: {{ .Values.loggingOperator.tls.fluentdSecretName | default (printf "%s-%s" (include "logging-demo.name" . ) "fluentd-tls" ) }}
      sharedKey: "{{ .Values.loggingOperator.tls.sharedKey }}"
    {{- end }}
    {{- if .Values.loggingOperator.fluentd }}
{{ toYaml .Values.loggingOperator.fluentd | indent 4}}
    {{- end}}

  fluentbit:
{{/*    security:*/}}
{{/*      podSecurityContext:*/}}
{{/*        runAsNonRoot: true*/}}
{{/*    metrics:*/}}
{{/*      serviceMonitor: true*/}}
{{/*      prometheusAnnotations: true*/}}
{{/*      port: 24231*/}}
{{/*      path: "/metrics"*/}}
{{/*      timeout: "30s"*/}}
{{/*      interval: "15s"*/}}

    {{- if .Values.loggingOperator.tls.enabled }}
    tls:
      enabled: true
      secretName: {{ .Values.loggingOperator.tls.fluentbitSecretName | default (printf "%s-%s" (include "logging-demo.name" . ) "fluentbit-tls" ) }}
      sharedKey: "{{ .Values.loggingOperator.tls.sharedKey }}"
    {{- end }}
    {{- if .Values.loggingOperator.fluentbit }}
{{ toYaml .Values.loggingOperator.fluentbit | indent 4}}
    {{- end}}
  nodeAgents:
    - name: testanyad
      type: windows
{{/*      nodeAgentFluentbit:*/}}
{{/*        security:*/}}
{{/*          podSecurityContext:*/}}
{{/*            runAsNonRoot: true*/}}
{{/*        metrics:*/}}
{{/*          serviceMonitor: true*/}}
{{/*          prometheusAnnotations: true*/}}
{{/*          port: 24231*/}}
{{/*          path: "/metrics"*/}}
{{/*          timeout: "30s"*/}}
{{/*          interval: "15s"*/}}

  controlNamespace: {{ .Values.loggingOperator.controlNamespace | default .Release.Namespace }}
